server:
  port: 8083

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/t_danger
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres

#spring:
#
#  jpa:
#    hibernate:
#      ddl-auto: create
#      dialect: org.hibernate.dialect.PostgreSQL94Dialect
#    database: POSTGRESQL
#    open-in-view: true
#  sql:
#    init:
#      platform: postgres
#  datasource:
#    driverClassName: org.postgresql.Driver
#    username: admin
#    password: admin
#    url: jdbc:postgresql://localhost:5432/danger?stringtype=unspecified