server:
  port: 8083

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:postgresql://localhost:5432/t_danger
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

security:
  jwt:
    secret-key: dGhpcyBpcyBteSBzZWN1cmUga2V5IGFuZCB5b3UgY2Fubm90IGhhY2sgaXQ

logging:
  level:
    org.springframework.security: TRACE